### ISSUE TITLE
formatCBMCOutput.py crashed

### ISSUE THREAD

**Issue by vmihalko** [aufover/cbmc-utils#2]
```console
$ cbmc-convert-output -a
Traceback (most recent call last):
  File "/usr/bin/cbmc-convert-output", line 140, in <module>
    print_it(parse_it())
  File "/usr/bin/cbmc-convert-output", line 105, in parse_it
    fun_name = source_loc['function']
KeyError: 'function'
```
reproducer:
```bash 
csmock -j8 -f -t cbmc --cbmc-add-flag '--div-by-zero-check --signed-overflow-check --unsigned-overflow-check --pointer-overflow-check --conversion-check --undefined-shift-check --float-overflow-check --nan-check' --cbmc-timeout 200 --keep-going --no-clean ./grep-3.6-2.fc34.src.rpm
```

**Comment by vmihalko** [comment]
This is caused by `--conversion-check`. I'm looking for small enough to read reproducer...
